### ISSUE TITLE
PandAの大規模改修により，Comfortable PandAが使えない

### ISSUE THREAD

**Issue by 1taroh** [das08/comfortable-panda#15]
今まで画面右上に出てきていたあれが表示されなくなっていました...
ちなみに4/8が講義開始です

**Comment by das08** [comment]
報告していただきありがとうございます。
対応いたします。

**Comment by das08** [comment]
対応完了しました。
https://github.com/comfortable-panda/ComfortablePandA-Extension/commit/b4337534afa43977ac9a614158c2e3a0eee6d20c
